import { cookieToInitialState } from 'wagmi';
import './globals.css';
import { getConfig } from '../../wagmi.config.mjs';
import { headers } from 'next/headers';
import { Providers } from './providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const initialState = cookieToInitialState(
    getConfig(),
    (await headers()).get('cookie')
  );
  return (
    <html lang="en">
      <body className={`antialiased sm:overflow-hidden overflow-auto`}>
        <Providers initialState={initialState}>{children}</Providers>
      </body>
    </html>
  );
}
